name: Lint Python Code

on:
  pull_request:
    branches:
      - github-actions
  push:
    branches:
      - github-actions
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Run Flake8
        run: |
          python3 -m venv venv
          . venv/bin/activate
          flake8 --exclude=venv --statistics
